### ISSUE TITLE
Create FullPage Styling option

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/pivottiles7#168]
## This was discovered on /sites/VIR/ CE Webpart
It can be found in the SiteAssets/virDashboard.js
It completely hides all the SharePoint part of the page.
All SharePoint is still there but the div just expands to cover the full screen

To apply this to a single webpart (like a "Expand Content" button, have to apply it here:

## Potential Prop Pane Properties and Integrations:

1. Allow Expando button
2. Default Load Page with Expanded (for single page apps)
3. Who can see the un-expand button (to hide site from normal users if there is no need)
4. Hard Code option to completely turn off in webpart.ts

## Banner Properties
Allow Expando button
Status of setting

![image](https://user-images.githubusercontent.com/49648086/154529184-7b752ca3-15cf-453b-ae4c-24eb648bb03e.png)

**NOTE**:  The SPO Sidebar (News, Sites, etc) is z-index 12.
```css
#ContainerDiv
{
	display: inline-block;
    position: fixed;
    top: 0%;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
	width: 100%
    //background-color: #f3f3f3;
	background-color: white;
	overflow-y: scroll ;
	//overflow-x: hidden ;
	z-index: 2;
}
```

There also is an icon bar inside the ContainerDiv

```css
.icon-bar {
  width: 100%;
  background-color: #305781;
  overflow: hidden;
  display:block;
  position: fixed;
  z-index: 2;
}

.icon-bar a {
  float: left;
  width: 5%;
  text-align: center;
  padding: 12px 0;
  transition: all 0.3s ease;
  color: white;
  font-size: 20px;
}
```
